const express = require("express")
const mongoose = require("mongoose")
const bodyParser = require("body-parser")
const cors = require("cors")
const app = express()
const userRoute = require("./routes/user")
app.use(bodyParser.urlencoded({extended:true}))
app.use(bodyParser.json())
app.use(cors())
app.use("/user",userRoute)
mongoose.connect("mongodb+srv://prajwal1927:prajwal24@cluster0.rctybvv.mongodb.net/?retryWrites=true&w=majority")
    .then(() => console.log("DB Connected"))
    .catch((err) => console.log(err.message))

app.listen(4000,()=>console.log("Server is running on Port 4000"))